[package]
name = "hibiki"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
default-run = "hibiki"

[[bin]]
name = "hibiki"
path = "src/main.rs"

[[bin]]
name = "hibiki-scdaemon"
path = "src/bin/scdaemon.rs"

[[bin]]
name = "hibiki-pinentry"
path = "src/bin/pinentry.rs"

[dependencies]
unicode-width = "0.2"
serde_json.workspace = true
chrono.workspace = true
ratatui.workspace = true
ratatui-image = { version = "=8.1.1", default-features = false, features = ["crossterm"] }
image = { version = "0.25", default-features = false }
base64.workspace = true
crossterm.workspace = true
hibiki-core.workspace = true
hibiki-lib.workspace = true
anyhow.workspace = true
serde.workspace = true
toml.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tokio-tungstenite.workspace = true
futures-util.workspace = true
clap.workspace = true
anstream.workspace = true
anstyle.workspace = true
tempfile.workspace = true
fs2.workspace = true
libc.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

zeroize.workspace = true
