[package]
name = "hibiki-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
hibiki-lib.workspace = true
anyhow.workspace = true
serde.workspace = true
toml.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tokio-tungstenite.workspace = true
futures-util.workspace = true
tempfile.workspace = true
fs2.workspace = true
libc.workspace = true
url.workspace = true
tracing.workspace = true
zeroize.workspace = true
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
