[package]
name = "hibiki-lib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
qrcode = { version = "0.14", default-features = false }
png = "0.18"
thiserror.workspace = true
serde.workspace = true
postcard.workspace = true
prost.workspace = true
snow.workspace = true
ed25519-dalek.workspace = true
getrandom.workspace = true
sha2.workspace = true
hex.workspace = true
base64.workspace = true
bip39.workspace = true
zeroize.workspace = true
libc.workspace = true

[build-dependencies]
prost.workspace = true
prost-types = "0.14"
prost-build.workspace = true
protoc-bin-vendored.workspace = true

[dev-dependencies]
prost-types = "0.14"
